/*
FORCESNLPsolver3 : A fast customized optimization solver.

Copyright (C) 2013-2022 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.0.0 on Wednesday, August 24, 2022 at 7:55:52 AM */
#ifndef FORCESNLPsolver3_H
#define FORCESNLPsolver3_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif
#ifndef SOLVER_STRING_H
#define SOLVER_STRING_H
#include <string.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double FORCESNLPsolver3_float;
typedef double FORCESNLPsolver3_ldl_s_float;
typedef double FORCESNLPsolver3_ldl_r_float;
typedef double FORCESNLPsolver3_callback_float;

typedef double FORCESNLPsolver3interface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_FORCESNLPsolver3
#define MISRA_C_FORCESNLPsolver3 (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_FORCESNLPsolver3
#define RESTRICT_CODE_FORCESNLPsolver3 (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_FORCESNLPsolver3
#define SET_PRINTLEVEL_FORCESNLPsolver3    (0)
#endif

/* timing */
#ifndef SET_TIMING_FORCESNLPsolver3
#define SET_TIMING_FORCESNLPsolver3    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_FORCESNLPsolver3			(200)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_FORCESNLPsolver3		(FORCESNLPsolver3_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_FORCESNLPsolver3	(200) 

/* maximum number of supported elements in the filter */
#define MAX_SOC_IT_FORCESNLPsolver3			(4) 

/* desired relative duality gap */
#define SET_ACC_RDGAP_FORCESNLPsolver3		(FORCESNLPsolver3_float)(0.0001)

/* desired maximum residual on equality constraints */
#define SET_ACC_RESEQ_FORCESNLPsolver3		(FORCESNLPsolver3_float)(1E-06)

/* desired maximum residual on inequality constraints */
#define SET_ACC_RESINEQ_FORCESNLPsolver3	(FORCESNLPsolver3_float)(1E-06)

/* desired maximum violation of complementarity */
#define SET_ACC_KKTCOMPL_FORCESNLPsolver3	(FORCESNLPsolver3_float)(1E-06)


/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_FORCESNLPsolver3      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_FORCESNLPsolver3 (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_FORCESNLPsolver3   (2)

/* solver stopped externally */
#define EXIT_EXTERNAL_FORCESNLPsolver3 (3)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_FORCESNLPsolver3  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_FORCESNLPsolver3   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_FORCESNLPsolver3  (-6)

/* no progress in method possible */
#define NOPROGRESS_FORCESNLPsolver3   (-7)

/* regularization error */
#define REGULARIZATION_ERROR_FORCESNLPsolver3   (-9)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_FORCESNLPsolver3   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_FORCESNLPsolver3   (-12)

/* thread error */
#define THREAD_FAILURE_FORCESNLPsolver3  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_FORCESNLPsolver3  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_FORCESNLPsolver3  (-100)

/* Insufficient number of internal memory instances.
 * Increase codeoptions.max_num_mem. */
#define MEMORY_INVALID_FORCESNLPsolver3 (-101)
/* Number of threads larger than specified.
 * Increase codeoptions.nlp.max_num_threads. */
#define NUMTHREADS_INVALID_FORCESNLPsolver3 (-102)

/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)


/* MEMORY STRUCT --------------------------------------------------------*/
typedef struct FORCESNLPsolver3_mem FORCESNLPsolver3_mem;
#ifdef __cplusplus
extern "C" {
#endif
/* MEMORY STRUCT --------------------------------------------------------*/
extern FORCESNLPsolver3_mem * FORCESNLPsolver3_external_mem(void * mem_ptr, solver_int32_unsigned i_mem, size_t mem_size);
extern size_t FORCESNLPsolver3_get_mem_size( void );
extern size_t FORCESNLPsolver3_get_const_size( void );
#ifdef __cplusplus
}
#endif

/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 6 */
    FORCESNLPsolver3_float xinit[6];

    /* vector of size 80 */
    FORCESNLPsolver3_float x0[80];

    /* vector of size 192 */
    FORCESNLPsolver3_float all_parameters[192];


} FORCESNLPsolver3_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* vector of size 10 */
    FORCESNLPsolver3_float x1[10];

    /* vector of size 10 */
    FORCESNLPsolver3_float x2[10];

    /* vector of size 10 */
    FORCESNLPsolver3_float x3[10];

    /* vector of size 10 */
    FORCESNLPsolver3_float x4[10];

    /* vector of size 10 */
    FORCESNLPsolver3_float x5[10];

    /* vector of size 10 */
    FORCESNLPsolver3_float x6[10];

    /* vector of size 10 */
    FORCESNLPsolver3_float x7[10];

    /* vector of size 10 */
    FORCESNLPsolver3_float x8[10];


} FORCESNLPsolver3_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* iteration number */
    solver_int32_default it;

	/* number of iterations needed to optimality (branch-and-bound) */
	solver_int32_default it2opt;
	
    /* inf-norm of equality constraint residuals */
    FORCESNLPsolver3_float res_eq;
	
    /* inf-norm of inequality constraint residuals */
    FORCESNLPsolver3_float res_ineq;

	/* norm of stationarity condition */
    FORCESNLPsolver3_float rsnorm;

	/* max of all complementarity violations */
    FORCESNLPsolver3_float rcompnorm;

    /* primal objective */
    FORCESNLPsolver3_float pobj;	
	
    /* dual objective */
    FORCESNLPsolver3_float dobj;	

    /* duality gap := pobj - dobj */
    FORCESNLPsolver3_float dgap;		
	
    /* relative duality gap := |dgap / pobj | */
    FORCESNLPsolver3_float rdgap;		

    /* duality measure */
    FORCESNLPsolver3_float mu;

	/* duality measure (after affine step) */
    FORCESNLPsolver3_float mu_aff;
	
    /* centering parameter */
    FORCESNLPsolver3_float sigma;
	
    /* number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;
    
    /* number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;
    
    /* step size (affine direction) */
    FORCESNLPsolver3_float step_aff;
    
    /* step size (combined direction) */
    FORCESNLPsolver3_float step_cc;    

	/* solvertime */
	FORCESNLPsolver3_float solvetime;   

	/* time spent in function evaluations */
	FORCESNLPsolver3_float fevalstime;  

    /* solver ID of FORCESPRO solver */
    solver_int32_default solver_id[8];  


} FORCESNLPsolver3_info;









/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Wednesday, August 24, 2022 7:55:52 AM */
/* User License expires on: (UTC) Friday, February 10, 2023 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Friday, February 10, 2023 10:00:00 PM (approx.) */
/* Solver Id: 9b5d5f99-7761-4b3c-801e-14915dc3df74 */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef solver_int32_default (*FORCESNLPsolver3_extfunc)(FORCESNLPsolver3_float* x, FORCESNLPsolver3_float* y, FORCESNLPsolver3_float* lambda, FORCESNLPsolver3_float* params, FORCESNLPsolver3_float* pobj, FORCESNLPsolver3_float* g, FORCESNLPsolver3_float* c, FORCESNLPsolver3_float* Jeq, FORCESNLPsolver3_float* h, FORCESNLPsolver3_float* Jineq, FORCESNLPsolver3_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default FORCESNLPsolver3_solve(FORCESNLPsolver3_params *params, FORCESNLPsolver3_output *output, FORCESNLPsolver3_info *info, FORCESNLPsolver3_mem *mem, FILE *fs, FORCESNLPsolver3_extfunc evalextfunctions_FORCESNLPsolver3);





/*Integrator declarations */
typedef const solver_int32_default* (*cDynJacXsparsity)( solver_int32_default i );
typedef const solver_int32_default* (*cDynJacUsparsity)( solver_int32_default i );
typedef solver_int32_default (*fConDynamics)( const FORCESNLPsolver3_callback_float** arg, FORCESNLPsolver3_callback_float** res, solver_int32_default* iw, FORCESNLPsolver3_callback_float* w, solver_int32_default mem );
typedef solver_int32_default (*fConJacStateDynamics)( const FORCESNLPsolver3_callback_float** arg, FORCESNLPsolver3_callback_float** res, solver_int32_default* iw, FORCESNLPsolver3_callback_float* w, solver_int32_default mem );
typedef solver_int32_default (*fConJacInputDynamics)( const FORCESNLPsolver3_callback_float** arg, FORCESNLPsolver3_callback_float** res, solver_int32_default* iw, FORCESNLPsolver3_callback_float* w, solver_int32_default mem );

void FORCESNLPsolver3_rkfour_0(const FORCESNLPsolver3_callback_float * const z, const FORCESNLPsolver3_callback_float * const p, FORCESNLPsolver3_float * const c, FORCESNLPsolver3_float * const jacc,
            fConDynamics cDyn0rd, fConDynamics cDyn, const solver_int32_default threadID);









#ifdef __cplusplus
}
#endif

#endif
